### ISSUE TITLE
 'utf-8' codec can't decode byte 0xe3 in position 3815: invalid continuation byte

### ISSUE THREAD

**Issue by BrixSat** [radujica/tospotify#16]
Hello I get this error on windows or debian.

user@DESKTOP-H87NGVR:/mnt/c/Users/user/Desktop/toSpotify$ tospotify 1167047623 mp3tag2.m3u
Traceback (most recent call last):
  File "/home/user/.local/bin/tospotify", line 10, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.7/site-packages/tospotify/run.py", line 87, in main
    update_spotify_playlist(spot, playlist_path, playlist_id, args.convert)
  File "/home/user/.local/lib/python3.7/site-packages/tospotify/search.py", line 120, in update_spotify_playlist
    songs = parse_songs(playlist_path)
  File "/home/user/.local/lib/python3.7/site-packages/tospotify/parser.py", line 33, in parse_songs
    playlist = m3u8.load(playlist_path)
  File "/home/user/.local/lib/python3.7/site-packages/m3u8/__init__.py", line 49, in load
    return _load_from_file(uri, custom_tags_parser)
  File "/home/user/.local/lib/python3.7/site-packages/m3u8/__init__.py", line 54, in _load_from_file
    raw_content = fileobj.read().strip()
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 3815: invalid continuation byte

**Comment by BrixSat** [comment]
This has to do with the content of the m3u8 playlist file. Fixed by removing all lines and tested with only one song.
