### ISSUE TITLE
Errors while testing with valid_playlist.m3u

### ISSUE THREAD

**Issue by pmtek** [radujica/tospotify#20]
Is this still working? I am getting errors when trying the valid_playlist.m3u file. I tried using tospotify 0.3.1 on Windows 10 with Python 3.6.0, 3.10.4 and 3.12.0. Here is the output.

```
Python 3.10.4
tospotify 0.3.1

INFO:root:Created playlist with name=valid_playlist at id=REDACTED
Traceback (most recent call last):
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python310\Scripts\tospotify.exe\__main__.py", line 7, in <module>
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python310\lib\site-packages\tospotify\run.py", line 87, in main
    update_spotify_playlist(spot, playlist_path, playlist_id, args.convert)
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python310\lib\site-packages\tospotify\search.py", line 120, in update_spotify_playlist
    songs = parse_songs(playlist_path)
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python310\lib\site-packages\tospotify\parser.py", line 33, in parse_songs
    playlist = m3u8.load(playlist_path)
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python310\lib\site-packages\m3u8\__init__.py", line 96, in load
    content, base_uri = http_client.download(uri, timeout, headers, verify_ssl)
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python310\lib\site-packages\m3u8\httpclient.py", line 16, in download
    resource = opener.open(uri, timeout=timeout)
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 541, in _open
    return self._call_chain(self.handle_open, 'unknown',
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1419, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: c>
```

**Comment by radujica** [comment]
Well caught :)

Looks like recent releases of m3u8 (>3.4.0) handle paths differently, hence this odd error.

I released patch 0.3.2 which puts a cap on the m3u8 version, so it should be working fine now (on Python >=3.7 at least).

Please re-open if this still causes issues and don't hesitate to open more if you spot other problems 👍 The project hasn't received much attention lately indeed; am raising a few issues myself.
