### ISSUE TITLE
ValueError: could not convert string to float: ''

### ISSUE THREAD

**Issue by unicav** [radujica/tospotify#27]
Ubuntu 22.04
Python 3.10.12

INFO:root:Created playlist with name=Test at id=4rkgtHurcTnsGjp7lHNFMr
Traceback (most recent call last):
  File "/usr/local/bin/tospotify", line 8, in <module>
    sys.exit(main())
  File "/home/serenity/.local/lib/python3.10/site-packages/tospotify/run.py", line 87, in main
    update_spotify_playlist(spot, playlist_path, playlist_id, args.convert)
  File "/home/serenity/.local/lib/python3.10/site-packages/tospotify/search.py", line 120, in update_spotify_playlist
    songs = parse_songs(playlist_path)
  File "/home/serenity/.local/lib/python3.10/site-packages/tospotify/parser.py", line 33, in parse_songs
    playlist = m3u8.load(playlist_path)
  File "/home/serenity/.local/lib/python3.10/site-packages/m3u8/__init__.py", line 49, in load
    return _load_from_file(uri, custom_tags_parser)
  File "/home/serenity/.local/lib/python3.10/site-packages/m3u8/__init__.py", line 56, in _load_from_file
    return M3U8(raw_content, base_uri=base_uri, custom_tags_parser=custom_tags_parser)
  File "/home/serenity/.local/lib/python3.10/site-packages/m3u8/model.py", line 153, in __init__
    self.data = parse(content, strict, custom_tags_parser)
  File "/home/serenity/.local/lib/python3.10/site-packages/m3u8/parser.py", line 143, in parse
    _parse_extinf(line, data, state, lineno, strict)
  File "/home/serenity/.local/lib/python3.10/site-packages/m3u8/parser.py", line 261, in _parse_extinf
    state['segment']['duration'] = float(duration)
ValueError: could not convert string to float: ''

**Comment by radujica** [comment]
Does the playlist file contain a `#EXTINF:` entry without any number of seconds, such as `#EXTINF:123`?

According to https://en.wikipedia.org/wiki/M3U that's invalid, so the error is correct.

**Comment by unicav** [comment]
Indeed it does. The 3 songs I added to test with all read -  #EXTINF:,Crazy
Talk
I'll have to look into how to fix that. I created the m3u with Rhythmbox.
Would be handy if you could catch the error and define it - i.e. "Invalid
M3U data" or even "Invalid #EXTINF in M3U"
Thanks for the info!

**Comment by radujica** [comment]
`tospotify` relies fully on [m3u8](https://pypi.org/project/m3u8/) for parsing. Will see if an improved error message can be added there, but otherwise I count this as closed.

Perhaps, for `tospotify`, consider using another playlist-making app that would handle this scenario. Cheers!
