### ISSUE TITLE
C:\ is replaced with current directory

### ISSUE THREAD

**Issue by BinToss** [radujica/tospotify#30]
```log
# Given pwd is HOME
tospotify --public --playlist-id 76EnUBXM3JIGN9L9YbXleN 1274469315 "C:\MEGA\Music\Jafet Meza\Halo\SPV3\mp3tag.m3u8"
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Noah\AppData\Roaming\Python\Python312\Scripts\tospotify.exe\__main__.py", line 7, in <module>
  File "C:\Users\Noah\AppData\Roaming\Python\Python312\site-packages\tospotify\run.py", line 87, in main
    update_spotify_playlist(spot, playlist_path, playlist_id, args.convert)
  File "C:\Users\Noah\AppData\Roaming\Python\Python312\site-packages\tospotify\search.py", line 120, in update_spotify_playlist
    songs = parse_songs(playlist_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noah\AppData\Roaming\Python\Python312\site-packages\tospotify\parser.py", line 33, in parse_songs
    playlist = m3u8.load(playlist_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noah\AppData\Roaming\Python\Python312\site-packages\m3u8\__init__.py", line 49, in load
    return _load_from_file(uri, custom_tags_parser)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noah\AppData\Roaming\Python\Python312\site-packages\m3u8\__init__.py", line 53, in _load_from_file
    with open(uri, encoding='utf8') as fileobj:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Noah\\MEGA\\Music\\Jafet Meza\\Halo\\SPV3\\mp3tag.m3u8'
```

**Comment by radujica** [comment]
@BinToss Both this and the other issue should be solved in 0.3.4.

Thanks again for raising them :)
